#!/usr/bin/env python3
"""generate_blueprint.py — Unified blueprint generator for both Part 1
(reconstructed-from-export) and Part 2 (Cowork-native) projects.

Reads disk-resident data only. No Cowork-session-context dependency. The
hub-side orchestrator (SKILL.md Step 2 / Step 3) invokes this script once
per project after all dumps and reconstruction are complete.

Mechanical sections (Section 2 Custom Instructions, Section 5 Knowledge
Base, Section 7 memory-restore preamble) are filled in directly from
disk inputs. Synthesis-required sections (1 Purpose, 3 Key Decisions, 4
WIP, 6 Recurring Context narrative) are emitted with clear TODO markers
that point to a sibling _BLUEPRINT_SYNTHESIS_NOTES.md file containing
raw input excerpts (transcript opener + closer message, full memory
entry bodies, knowledge file previews). The hub Claude reads that notes
file as context and writes the final synthesis into the blueprint.

Output:
    <project_dir>/transition-data/project-blueprint.md
    <project_dir>/transition-data/_BLUEPRINT_SYNTHESIS_NOTES.md

Usage:

    python3 generate_blueprint.py \\
        --project-dir <path> \\
        --type        <part1|part2> \\
        [--export-project-json <path>]   (Part 1 only; optional but recommended)
        [--name       <display name>]    (default: folder name)

Where:
    --project-dir         The project folder. For Part 1 this is the
                          reconstructed folder; for Part 2 it's the
                          existing Cowork project folder.
    --type                Explicit project type. Drives input expectations.
                          part1: expects knowledge/, conversation-history/,
                                 optionally an export project JSON.
                          part2: expects working-folder root files,
                                 optionally conversation-history/
                                 (dumped session transcripts) and
                                 transition-data/cowork-space-memory/
                                 (dumped Cowork memory).
    --export-project-json Path to the project's JSON from the export's
                          projects/ folder (only meaningful for part1).
                          Provides custom instructions (prompt_template)
                          and the canonical display name. Optional —
                          script proceeds with reasonable defaults if
                          omitted.
    --name                Override the project's display name. Defaults
                          to the project folder's name.
"""

import argparse
import json
import sys
from datetime import datetime
from pathlib import Path


# Files at the root of any project folder that are considered "working files"
# for the purpose of Section 5 inventory (Part 2 case).
WORKING_FILE_EXTS = {".md", ".txt", ".html", ".docx", ".xlsx", ".pdf",
                     ".csv", ".json", ".yaml", ".yml", ".py", ".js",
                     ".ts", ".sh", ".ps1", ".sql"}

# Files / folder names to exclude from working-files inventory — these are
# generated by the migration skill itself or are internal artifacts. NEVER
# add user-content filenames here (e.g. README.md, CHANGELOG.md, NOTES.md)
# — those are the user's working files and belong in the inventory. The
# skill's own files are deliberately prefixed with `_` (or live in
# transition-data/) to keep them distinguishable from user content.
WORKING_FILE_SKIP_NAMES = {
    "_PROJECT_BRIEF.md",
    "_ARTIFACTS_TO_RECOVER.md",
    "_BLUEPRINT_SYNTHESIS_NOTES.md",
    "_MIGRATION_NOTE.md",
}
WORKING_FILE_SKIP_DIRS = {
    "transition-data",
    "conversation-history",
    "knowledge",
    ".git", "__pycache__", "node_modules",
}


def find_restore_preamble():
    """Locate and read the memory-restore preamble from the bundle's assets.

    Returns the verbatim STEPS 1-5 fenced block content from
    cowork-memory-restore-prompt.md, suitable for embedding into Section 7.
    """
    # Script lives at <bundle>/scripts/; asset lives at <bundle>/assets/.
    asset_path = Path(__file__).resolve().parent.parent / "assets" / "cowork-memory-restore-prompt.md"
    if not asset_path.is_file():
        # Graceful degradation: skip preamble, mark with placeholder.
        return None
    text = asset_path.read_text(encoding="utf-8")
    # The asset wraps the prompt in a triple-backtick fenced block.
    # Extract the content between the first fenced block delimiters.
    in_fence = False
    lines = []
    for line in text.splitlines():
        if line.strip().startswith("```"):
            if in_fence:
                break  # closing fence found; we've captured the body
            in_fence = True
            continue
        if in_fence:
            lines.append(line)
    if not lines:
        return None
    return "\n".join(lines).rstrip()


def collect_part1_inputs(project_dir, export_project_json_path):
    """Gather Part 1 (reconstructed-from-export) inputs.

    Returns a dict with: name, custom_instructions, knowledge_files,
    transcript_files, working_files, memory_entries.
    """
    result = {
        "name": None,
        "custom_instructions": None,
        "knowledge_files": [],
        "transcript_files": [],
        "working_files": [],
        "memory_entries": [],
        "project_uuid": None,
        "description": None,
    }

    # Project JSON gives us name + custom instructions + canonical knowledge list.
    project_json = None
    if export_project_json_path and Path(export_project_json_path).is_file():
        try:
            project_json = json.loads(
                Path(export_project_json_path).read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            project_json = None

    if project_json:
        result["name"] = project_json.get("name") or None
        result["project_uuid"] = project_json.get("uuid") or None
        result["description"] = (project_json.get("description") or "").strip() or None
        instr = (project_json.get("prompt_template") or "").strip()
        if instr:
            result["custom_instructions"] = instr

    # Knowledge files: read what's actually in knowledge/ on disk (the
    # reconstructed source-of-truth).
    knowledge_dir = project_dir / "knowledge"
    if knowledge_dir.is_dir():
        for p in sorted(knowledge_dir.iterdir()):
            if p.is_file():
                size = p.stat().st_size
                preview = read_preview(p)
                result["knowledge_files"].append({
                    "filename": p.name,
                    "size_bytes": size,
                    "preview": preview,
                })

    # Transcript files in conversation-history/.
    result["transcript_files"] = collect_transcripts(project_dir)

    # Memory entries (Part 1 typically has none, but handle if present).
    result["memory_entries"] = collect_memory_entries(project_dir)

    return result


def collect_part2_inputs(project_dir):
    """Gather Part 2 (Cowork-native) inputs.

    Returns a dict with the same shape as collect_part1_inputs.
    """
    result = {
        "name": None,
        "custom_instructions": None,
        "knowledge_files": [],
        "transcript_files": [],
        "working_files": [],
        "memory_entries": [],
        "project_uuid": None,
        "description": None,
    }

    # Custom instructions: Part 2 doesn't have a prompt_template field
    # (Cowork projects don't have one). Look for a document at the project
    # root whose name suggests it (custom-instructions.md, instructions.md,
    # CUSTOM_INSTRUCTIONS.md, etc.).
    for candidate in ("custom-instructions.md", "CUSTOM_INSTRUCTIONS.md",
                      "instructions.md", "INSTRUCTIONS.md",
                      "custom_instructions.md"):
        p = project_dir / candidate
        if p.is_file():
            result["custom_instructions"] = p.read_text(encoding="utf-8").strip()
            break

    # Working files at the project root.
    if project_dir.is_dir():
        for p in sorted(project_dir.iterdir()):
            if p.is_dir() and p.name in WORKING_FILE_SKIP_DIRS:
                continue
            if not p.is_file():
                continue
            if p.name in WORKING_FILE_SKIP_NAMES:
                continue
            if p.suffix.lower() not in WORKING_FILE_EXTS:
                continue
            size = p.stat().st_size
            preview = read_preview(p) if p.suffix.lower() in {".md", ".txt"} else ""
            result["working_files"].append({
                "filename": p.name,
                "size_bytes": size,
                "preview": preview,
            })

    # Conversation-history holds the dumped Cowork session transcripts (and
    # any prior web-chat conversations if the project was hybrid).
    result["transcript_files"] = collect_transcripts(project_dir)

    # Cowork memory dump (per-project).
    result["memory_entries"] = collect_memory_entries(project_dir)

    return result


def collect_transcripts(project_dir):
    """List the .md files in conversation-history/ with basic metadata."""
    out = []
    ch = project_dir / "conversation-history"
    if not ch.is_dir():
        return out
    for p in sorted(ch.iterdir()):
        if not p.is_file() or p.suffix.lower() != ".md":
            continue
        if p.name == "INDEX.md":
            continue
        try:
            text = p.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        line_count = text.count("\n") + 1
        out.append({
            "filename": p.name,
            "size_bytes": p.stat().st_size,
            "line_count": line_count,
            "first_user_message": extract_first_user_message(text),
            "last_user_message": extract_last_user_message(text),
        })
    return out


def collect_memory_entries(project_dir):
    """List the .md files in transition-data/cowork-space-memory/."""
    out = []
    mem_dir = project_dir / "transition-data" / "cowork-space-memory"
    if not mem_dir.is_dir():
        return out
    for p in sorted(mem_dir.iterdir()):
        if not p.is_file() or p.suffix.lower() != ".md":
            continue
        if p.name == "MEMORY.md":
            # Index file — note its presence but don't treat as a memory entry.
            continue
        try:
            text = p.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        out.append({
            "filename": p.name,
            "size_bytes": p.stat().st_size,
            "body": text,
        })
    return out


def read_preview(path, max_chars=200):
    """Read the first max_chars characters of a file (for inventory previews)."""
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return ""
    return text[:max_chars].replace("\n", " ").strip()


def extract_first_user_message(transcript_text, max_chars=300):
    """Try to find the first user message in a transcript.

    The Part 1 transcript format uses '### human  ·  <ts>' as the role
    header. The Part 2 transcript format (from mcp__session_info__read_transcript)
    uses '[user]' prefixes. Try both heuristics.
    """
    lines = transcript_text.splitlines()
    in_user_block = False
    user_lines = []
    for line in lines:
        stripped = line.strip()
        if stripped.startswith("### human") or stripped.startswith("[user]"):
            if user_lines:
                break
            in_user_block = True
            continue
        if in_user_block:
            if stripped.startswith("###") or stripped.startswith("["):
                break
            if stripped:
                user_lines.append(stripped)
                if sum(len(s) for s in user_lines) > max_chars:
                    break
    text = " ".join(user_lines)[:max_chars]
    return text


def extract_last_user_message(transcript_text, max_chars=300):
    """Same as extract_first_user_message but for the LAST user message."""
    lines = transcript_text.splitlines()
    last_user_lines = []
    current_user_lines = []
    in_user_block = False
    for line in lines:
        stripped = line.strip()
        if stripped.startswith("### human") or stripped.startswith("[user]"):
            if current_user_lines:
                last_user_lines = current_user_lines
            current_user_lines = []
            in_user_block = True
            continue
        if stripped.startswith("### assistant") or stripped.startswith("[assistant]"):
            if current_user_lines:
                last_user_lines = current_user_lines
            in_user_block = False
            continue
        if in_user_block and stripped:
            current_user_lines.append(stripped)
    if current_user_lines:
        last_user_lines = current_user_lines
    text = " ".join(last_user_lines)[:max_chars]
    return text


def render_blueprint(project_name, project_type, inputs, restore_preamble):
    """Build the project-blueprint.md content as a list of lines."""
    lines = []
    lines.append(f"# Project Blueprint: {project_name}")
    lines.append("")
    lines.append(f"*Project type: {project_type}*")
    if inputs.get("project_uuid"):
        lines.append(f"*Source project UUID: `{inputs['project_uuid']}`*")
    lines.append("")
    lines.append("**How to use this file:**")
    lines.append("")
    lines.append("- **You (the user)** paste **Section 2 (\"Custom Instructions\") verbatim**")
    lines.append("  into the new Cowork project's settings field. If Section 2 is blank,")
    lines.append("  the source had no Custom Instructions — skip this step. Then paste")
    lines.append("  the short bootstrap prompt the migration skill (or this folder's")
    lines.append("  `_RESUME_ON_NEW_ACCOUNT.md` / hub `README - Final Transition to New")
    lines.append("  Account.md`) gives you as the first message in a fresh conversation")
    lines.append("  in the new project.")
    lines.append("- **Claude (in the new conversation)** reads this entire blueprint and")
    lines.append("  uses **Section 7 (\"Recommended Starting Prompt\")** as its first")
    lines.append("  directive. For migrated Cowork projects, Section 7 restores any dumped")
    lines.append("  per-project memory before the project-tailored steps.")
    lines.append("")
    lines.append("The other sections — Purpose, Key Decisions, Work in Progress, Knowledge")
    lines.append("Base Contents, Recurring Context — give Claude narrative context for the")
    lines.append("project. They are read as context once the conversation is in motion,")
    lines.append("not pasted anywhere.")
    lines.append("")

    # Section 1
    lines.append("## 1. Purpose")
    lines.append("")
    if inputs.get("description"):
        lines.append(f"**Description (from export):** {inputs['description']}")
        lines.append("")
    lines.append("> **TODO — synthesize:** What is this project for? What was the user")
    lines.append("> working on, and where were they trying to get to? Pull from the")
    lines.append("> opening user message of each conversation, the custom-instructions")
    lines.append("> framing, and any memory entries describing project intent. Aim for")
    lines.append("> 2-4 sentences. See `_BLUEPRINT_SYNTHESIS_NOTES.md` Section 1.")
    lines.append("")

    # Section 2
    lines.append("## 2. Custom Instructions")
    lines.append("")
    if inputs.get("custom_instructions"):
        lines.append("Paste the fenced block below into the new project's **Custom**")
        lines.append("**Instructions** field (no commentary, no quotation marks — just the")
        lines.append("text between the fence lines):")
        lines.append("")
        lines.append("```")
        lines.append(inputs["custom_instructions"])
        lines.append("```")
    else:
        lines.append("*(no custom instructions on source; leave the new project's settings empty)*")
    lines.append("")

    # Section 3
    lines.append("## 3. Key Decisions")
    lines.append("")
    lines.append("> **TODO — synthesize:** What decisions were made over the project's")
    lines.append("> lifespan that constrain or anchor future work? Locked architecture,")
    lines.append("> ruled-out approaches, naming conventions, deadlines. Pull from")
    lines.append("> memory entries (especially `feedback_*` and `project_*` entries) and")
    lines.append("> from late-conversation excerpts where decisions are typically")
    lines.append("> retrospected. See `_BLUEPRINT_SYNTHESIS_NOTES.md` Section 3.")
    lines.append("")

    # Section 4
    lines.append("## 4. Work in Progress")
    lines.append("")
    lines.append("> **TODO — synthesize:** What was the user actively doing at the end")
    lines.append("> of the source-account session history? Open threads, pending")
    lines.append("> reviews, unfinished drafts, work blocked on user action. Pull from")
    lines.append("> the LAST user message of each conversation — that's usually the")
    lines.append("> most recent unresolved item. See `_BLUEPRINT_SYNTHESIS_NOTES.md`")
    lines.append("> Section 4.")
    lines.append("")

    # Section 5
    lines.append("## 5. Knowledge Base")
    lines.append("")
    knowledge_files = inputs.get("knowledge_files", [])
    working_files = inputs.get("working_files", [])
    transcript_files = inputs.get("transcript_files", [])
    memory_entries = inputs.get("memory_entries", [])

    if knowledge_files:
        lines.append(f"**Knowledge documents ({len(knowledge_files)} in `knowledge/`):**")
        lines.append("")
        for k in knowledge_files:
            size_kb = k["size_bytes"] / 1024
            lines.append(f"- `{k['filename']}` — {size_kb:.1f} KB")
        lines.append("")

    if working_files:
        lines.append(f"**Working files at project root ({len(working_files)}):**")
        lines.append("")
        for w in working_files:
            size_kb = w["size_bytes"] / 1024
            lines.append(f"- `{w['filename']}` — {size_kb:.1f} KB")
        lines.append("")

    if transcript_files:
        lines.append(f"**Conversation history (`conversation-history/`): "
                     f"{len(transcript_files)} transcript(s).** "
                     f"See the folder's INDEX.md for the catalog.")
        lines.append("")

    if memory_entries:
        lines.append(f"**Cowork memory entries dumped from source account: "
                     f"{len(memory_entries)} (under `transition-data/cowork-space-memory/`).** "
                     f"Restored into the destination project's memory automatically "
                     f"by Section 7's memory-restore preamble (which runs first when "
                     f"the destination Claude follows Section 7 as its first directive).")
        lines.append("")

    if not (knowledge_files or working_files or transcript_files or memory_entries):
        lines.append("*(no knowledge, working files, transcripts, or memory entries detected)*")
        lines.append("")

    # Section 6
    lines.append("## 6. Recurring Context")
    lines.append("")
    if memory_entries:
        lines.append(f"This project's Cowork memory carries {len(memory_entries)} "
                     f"entries describing accumulated context — user-feedback rules, "
                     f"project-state facts, references to external systems. The entries "
                     f"are automatically restored into the destination project's memory "
                     f"by Section 7's memory-restore preamble (which runs first when "
                     f"the destination Claude follows Section 7 as its first directive). "
                     f"The hub Claude does not need to paraphrase or summarize them here "
                     f"— they live in memory and Claude in future sessions will see them "
                     f"in context.")
        lines.append("")
        lines.append("> **TODO — synthesize:** Briefly describe (1-3 sentences) what")
        lines.append("> *kind* of context the memory holds, so a fresh reader of this")
        lines.append("> blueprint knows what's being restored. Pull category counts from")
        lines.append("> the memory filenames (feedback_*, project_*, reference_*, user_*).")
        lines.append("> See `_BLUEPRINT_SYNTHESIS_NOTES.md` Section 6.")
    else:
        lines.append("*(no Cowork memory entries to restore)*")
        lines.append("")
        lines.append("> **TODO — synthesize:** What recurring context (terminology,")
        lines.append("> external systems, people, ongoing situations) does this project")
        lines.append("> rely on that a fresh-eyed reader wouldn't already know? Pull")
        lines.append("> from the custom instructions (Section 2) and any working files")
        lines.append("> at the project root.")
    lines.append("")

    # Section 7
    #
    # Design (v1.5.1+): Section 7 is no longer what the user pastes. The user
    # pastes a SHORT outer prompt (provided by the migration skill's locked
    # copy and by the manual-fallback docs) that tells the destination Claude
    # to read this blueprint and treat Section 7 as its first directive.
    # So Section 7 is framed as a directive TO Claude, not a paste target
    # for the user.
    #
    # Section 7 contents (in order):
    #   - Memory-restore preamble (verbatim STEPS 1-5) — ONLY when Cowork
    #     memory was dumped on the source side (memory_entries non-empty).
    #     Omitted entirely otherwise (no point making Claude run through a
    #     5-step procedure that will find nothing to restore).
    #   - Numbered directives:
    #       1. Project-specific reading list — TODO marker; synthesis-Claude
    #          fills based on Section 5 working files + Section 1 purpose.
    #       2. Register the pre-migration conversation archive as on-demand
    #          reference (memory entry) — templated; conversation count and
    #          migration-date slug substituted at generation time. Omitted
    #          when there's no conversation-history.
    #       3. Section 4 open items short summary — TODO marker; synthesis-
    #          Claude fills with one-liner per open item from Section 4.
    #       4. Acknowledgment back to user — static text.
    has_memory = bool(memory_entries)
    has_history = bool(transcript_files)
    migration_date_compact = datetime.now().strftime("%Y%m%d")
    archive_slug = f"reference_pre_migration_archive_{migration_date_compact}"

    lines.append("## 7. Recommended Starting Prompt")
    lines.append("")
    lines.append("**For Claude in the destination project:** Treat the following as your")
    lines.append("first directive after reading this blueprint. The user is pasting a")
    lines.append("short outer bootstrap prompt in chat that points at this section.")
    lines.append("")
    lines.append("```")

    item_number = 1

    # Memory-restore preamble — only when there's memory to restore.
    if has_memory:
        if restore_preamble:
            lines.append(restore_preamble)
            lines.append("")
            lines.append("---")
            lines.append("")
        else:
            # Asset wasn't found at generation time. Emit a clearly-marked
            # placeholder so the user can intervene before pasting.
            lines.append("[Memory-restore preamble would normally land here verbatim from")
            lines.append("the cowork-memory-restore-prompt.md asset. Asset was not found")
            lines.append("at generation time; insert manually before this section is used.]")
            lines.append("")
            lines.append("---")
            lines.append("")
        # After preamble, lead into the numbered directives.
        lines.append("Once memory is restored, resume the project:")
        lines.append("")
    else:
        # No memory to restore — open straight into the numbered directives.
        lines.append("Resume the project:")
        lines.append("")

    # Item 1 — project-specific reading list. TODO marker for synthesis.
    lines.append(f"{item_number}. [TODO — synthesize: project-specific reading list.")
    lines.append("   Identify the 2-3 working files most critical for orienting a fresh")
    lines.append("   session to this project. Pull from Section 5 (Knowledge Base")
    lines.append("   inventory) and Section 1 (Purpose). Be specific — name each file")
    lines.append("   rather than referring to folders generically. Format suggestion:")
    lines.append("   \"Read `FILE_A.md` first, then `FILE_B.md` and `FILE_C.md`, to load")
    lines.append("   the <conventions/context/state> for this <project type>.\"]")
    lines.append("")
    item_number += 1

    # Item 2 — register conversation-history as on-demand reference.
    # Only when conversation-history is present.
    if has_history:
        n_transcripts = len(transcript_files)
        transcript_word = "transcript" if n_transcripts == 1 else "transcripts"
        lines.append(f"{item_number}. Register the pre-migration conversation archive as on-demand")
        lines.append(f"   reference. `conversation-history/` (sibling folder to")
        lines.append(f"   `transition-data/`) contains {n_transcripts} session {transcript_word} from")
        lines.append(f"   the source account; `INDEX.md` catalogs them. Don't read every")
        lines.append(f"   transcript now — instead, write a memory entry:")
        lines.append("")
        lines.append(f"       Name: {archive_slug}")
        lines.append(f"       Type: reference")
        lines.append(f"       Body: This project's pre-migration conversation history")
        lines.append(f"       lives at `conversation-history/` (relative to the project")
        lines.append(f"       folder). INDEX.md catalogs each transcript with a one-line")
        lines.append(f"       description. Consult specific transcripts when context on")
        lines.append(f"       a pre-migration topic or decision would help — they are")
        lines.append(f"       reference material, not preload.")
        lines.append("")
        item_number += 1

    # Item 3 — Section 4 open items short summary. TODO marker for synthesis.
    lines.append(f"{item_number}. [TODO — synthesize: Section 4 open items short summary.")
    lines.append("   One-line summary per open item from Section 4 of this blueprint.")
    lines.append("   Format: \"The open items from Section 4 are: (1) <one-liner>,")
    lines.append("   (2) <one-liner>, (3) <one-liner>.\" Scale numbering to actual item")
    lines.append("   count. If Section 4 indicates work was completed at source, write:")
    lines.append("   \"Source-side work appears completed — confirm with me whether")
    lines.append("   there's outstanding follow-up.\"]")
    lines.append("")
    item_number += 1

    # Item 4 — acknowledgment. Static.
    if has_memory:
        lines.append(f"{item_number}. Confirm memory restored cleanly and the project frame is")
        lines.append("   loaded. Then ask me which thread to pick up.")
    else:
        lines.append(f"{item_number}. Confirm the project frame is loaded. Then ask me which")
        lines.append("   thread to pick up.")
    lines.append("```")
    lines.append("")

    return "\n".join(lines)


def render_synthesis_notes(project_name, project_type, inputs):
    """Build _BLUEPRINT_SYNTHESIS_NOTES.md content — raw input excerpts the
    hub Claude uses to write the TODO sections of the blueprint."""
    lines = []
    lines.append(f"# Blueprint Synthesis Notes: {project_name}")
    lines.append("")
    lines.append(f"*Project type: {project_type}*")
    lines.append("")
    lines.append("This file holds raw input excerpts the hub Claude uses to synthesize")
    lines.append("the TODO sections of `project-blueprint.md`. Read this file as")
    lines.append("context, write the synthesis directly into the blueprint, then")
    lines.append("optionally delete this file (or keep it as a record of the inputs).")
    lines.append("")

    knowledge_files = inputs.get("knowledge_files", [])
    working_files = inputs.get("working_files", [])
    transcript_files = inputs.get("transcript_files", [])
    memory_entries = inputs.get("memory_entries", [])

    # Section 1 / Section 4 helpers — transcript openers and closers.
    lines.append("## Section 1 + 4 inputs: transcript opener / closer messages")
    lines.append("")
    if not transcript_files:
        lines.append("*(no transcripts on disk)*")
        lines.append("")
    else:
        lines.append("For each transcript, the first and last user messages are excerpted")
        lines.append("below. The first message frames what the conversation was *about* (use")
        lines.append("for Section 1 Purpose); the last user message often signals what was")
        lines.append("*pending* at the end (use for Section 4 WIP).")
        lines.append("")
        for t in transcript_files:
            lines.append(f"### `{t['filename']}`")
            lines.append(f"*{t['line_count']} lines, {t['size_bytes']} bytes*")
            lines.append("")
            if t["first_user_message"]:
                lines.append("**First user message (opener):**")
                lines.append("")
                lines.append(f"> {t['first_user_message']}")
                lines.append("")
            if t["last_user_message"] and t["last_user_message"] != t["first_user_message"]:
                lines.append("**Last user message (closer):**")
                lines.append("")
                lines.append(f"> {t['last_user_message']}")
                lines.append("")

    # Section 3 / Section 6 inputs: memory entries.
    lines.append("## Section 3 + 6 inputs: Cowork memory entries (full bodies)")
    lines.append("")
    if not memory_entries:
        lines.append("*(no Cowork memory dumped from source account)*")
        lines.append("")
    else:
        lines.append("Each memory entry is reproduced verbatim below. Use these for:")
        lines.append("- **Section 3** (Key Decisions): `feedback_*` and `project_*`")
        lines.append("  entries usually carry locked decisions and their rationale.")
        lines.append("- **Section 6** (Recurring Context): describe what category of")
        lines.append("  context the memory holds (count by `feedback_`, `project_`,")
        lines.append("  `reference_`, `user_` prefixes).")
        lines.append("")
        for m in memory_entries:
            lines.append(f"### `{m['filename']}`")
            lines.append("")
            lines.append("```markdown")
            lines.append(m["body"].rstrip())
            lines.append("```")
            lines.append("")

    # Section 5 supporting data: knowledge + working files preview.
    lines.append("## Section 5 supporting data: knowledge and working files (previews)")
    lines.append("")
    if knowledge_files:
        lines.append("### Knowledge documents")
        lines.append("")
        for k in knowledge_files:
            size_kb = k["size_bytes"] / 1024
            lines.append(f"#### `{k['filename']}` — {size_kb:.1f} KB")
            if k["preview"]:
                lines.append("")
                lines.append(f"> {k['preview']}")
            lines.append("")
    if working_files:
        lines.append("### Working files at project root")
        lines.append("")
        for w in working_files:
            size_kb = w["size_bytes"] / 1024
            lines.append(f"#### `{w['filename']}` — {size_kb:.1f} KB")
            if w["preview"]:
                lines.append("")
                lines.append(f"> {w['preview']}")
            lines.append("")
    if not (knowledge_files or working_files):
        lines.append("*(no knowledge or working files detected)*")
        lines.append("")

    return "\n".join(lines)


def render_part2_project_brief(project_name, inputs):
    """Build _PROJECT_BRIEF.md content for a Part 2 (Cowork-native) project.

    Symmetric with reconstruct.py's write_project_brief for Part 1: gives the
    destination-side user (or future Claude) a quick orientation to what's
    in the folder and how to resume work. Mechanical inventory only; the
    actual synthesis lives in project-blueprint.md.
    """
    from datetime import datetime as _dt
    working_files = inputs.get("working_files", [])
    transcript_files = inputs.get("transcript_files", [])
    memory_entries = inputs.get("memory_entries", [])

    lines = [
        f"# {project_name}",
        "",
        "## Provenance",
        "- Source: Cowork-native project (carried across via account migration)",
        f"- Brief generated: {_dt.now().strftime('%Y-%m-%d %H:%M')}",
        "",
        "## Custom instructions (from source-account project settings)",
        "",
    ]
    if inputs.get("custom_instructions"):
        lines.append("Paste this verbatim into the new project's settings:")
        lines.append("")
        lines.append("```")
        lines.append(inputs["custom_instructions"])
        lines.append("```")
    else:
        lines.append("_(none detected at source — leave the new project's settings empty)_")
    lines += [
        "",
        "## Working files inventory",
        "",
    ]
    if working_files:
        lines.append(f"{len(working_files)} working file(s) at the project root:")
        lines.append("")
        for w in working_files:
            size_kb = w["size_bytes"] / 1024
            lines.append(f"- `{w['filename']}` — {size_kb:.1f} KB")
    else:
        lines.append("_(no working files at the project root)_")
    lines += [
        "",
        "## Conversation history",
        "",
    ]
    if transcript_files:
        lines.append(
            f"{len(transcript_files)} transcript(s) in `conversation-history/`. "
            f"See `conversation-history/INDEX.md` for the catalog.")
    else:
        lines.append("_(no session transcripts dumped from source)_")
    lines += [
        "",
        "## Cowork memory",
        "",
    ]
    if memory_entries:
        lines.append(
            f"{len(memory_entries)} memory entry/entries dumped from source "
            f"at `transition-data/cowork-space-memory/`. These restore "
            f"automatically into the destination project's per-project memory "
            f"when the user pastes the project blueprint's Section 7 "
            f"recommended starting prompt.")
    else:
        lines.append("_(no Cowork memory dumped from source — either nothing "
                     "was accumulated or the source memory directory was "
                     "empty)_")
    lines += [
        "",
        "## Resuming on the new account",
        "",
        "When you've imported this folder as a Cowork project on the new account",
        "(via **New project → Choose existing folder**):",
        "",
        "1. If `transition-data/project-blueprint.md` has a non-empty Section 2",
        "   (Custom Instructions), copy it verbatim into the new project's settings",
        "   (no commentary, no quotation marks — just the text between the fence lines).",
        "2. Start a fresh conversation in the project. Paste the following as the",
        "   first message:",
        "",
        "```",
        "This is a project I'm migrating from my old Claude account. Read",
        "`transition-data/project-blueprint.md` for the full project context,",
        "then treat its Section 7 — Recommended Starting Prompt — as your",
        "first directive.",
        "```",
        "",
        "Claude will read the blueprint, restore any dumped Cowork memory (per",
        "Section 7's directive), and pick up where the source-account version left",
        "off — no further setup needed.",
        "",
        "## Notes",
        "",
        "- This brief is generated by the project-import skill as a migration-time orientation aid. After the destination project is bootstrapped and verified, the brief has no load-bearing function — `CLAUDE.md` and the project's own structure take over the orientation role. **Both this `_PROJECT_BRIEF.md` and the `transition-data/` folder are safe to delete after verification.** Keep them as a migration record if you prefer; nothing depends on either going forward.",
        "- `transition-data/` holds migration-staging files (memory dump, blueprint, synthesis notes, tracker, _RESUME_ON_NEW_ACCOUNT.md). The `conversation-history/` folder is separate — keep that; Section 7's directive registers it as on-demand reference.",
    ]
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser(
        description=("Generate project-blueprint.md and "
                     "_BLUEPRINT_SYNTHESIS_NOTES.md for a project."))
    ap.add_argument("--project-dir", required=True,
                    help="The project folder to generate a blueprint for.")
    ap.add_argument("--type", required=True, choices=["part1", "part2"],
                    help="Project type. part1 = reconstructed from export; "
                         "part2 = Cowork-native.")
    ap.add_argument("--export-project-json", default=None,
                    help="Path to the project's JSON from the export's projects/ "
                         "folder. Used for prompt_template (Section 2) and canonical "
                         "display name. Part 1 only; optional.")
    ap.add_argument("--name", default=None,
                    help="Override the project's display name. "
                         "Default: folder name.")
    args = ap.parse_args()

    project_dir = Path(args.project_dir).resolve()
    if not project_dir.is_dir():
        print(f"ERROR: --project-dir is not a directory: {project_dir}",
              file=sys.stderr)
        return 1

    if args.type == "part1":
        inputs = collect_part1_inputs(project_dir, args.export_project_json)
    else:
        inputs = collect_part2_inputs(project_dir)

    # Resolve display name precedence: explicit --name > project JSON name >
    # folder name.
    name = args.name or inputs.get("name") or project_dir.name

    # Load the memory-restore preamble (for Section 7).
    restore_preamble = find_restore_preamble()

    # Render outputs.
    blueprint_text = render_blueprint(name, args.type, inputs, restore_preamble)
    notes_text = render_synthesis_notes(name, args.type, inputs)

    # Write outputs.
    transition_dir = project_dir / "transition-data"
    transition_dir.mkdir(parents=True, exist_ok=True)

    blueprint_path = transition_dir / "project-blueprint.md"
    notes_path = transition_dir / "_BLUEPRINT_SYNTHESIS_NOTES.md"

    blueprint_path.write_text(blueprint_text + "\n", encoding="utf-8")
    notes_path.write_text(notes_text + "\n", encoding="utf-8")

    # For Part 2 projects, also write a _PROJECT_BRIEF.md at the project root,
    # symmetric with what reconstruct.py produces for Part 1 projects. This
    # closes the manual-intervention gap from claude-a-handoff §Category 1 #3
    # (Part 2 briefs previously hand-written by Claude during dev).
    brief_path = None
    if args.type == "part2":
        brief_text = render_part2_project_brief(name, inputs)
        brief_path = project_dir / "_PROJECT_BRIEF.md"
        brief_path.write_text(brief_text + "\n", encoding="utf-8")

    # Summary.
    print(f"Project: {name}")
    print(f"  Type             : {args.type}")
    print(f"  Project folder   : {project_dir}")
    print(f"  Custom instr.    : "
          f"{'present' if inputs.get('custom_instructions') else 'absent'}")
    print(f"  Knowledge files  : {len(inputs.get('knowledge_files', []))}")
    print(f"  Working files    : {len(inputs.get('working_files', []))}")
    print(f"  Transcripts      : {len(inputs.get('transcript_files', []))}")
    print(f"  Memory entries   : {len(inputs.get('memory_entries', []))}")
    print(f"  Restore preamble : "
          f"{'embedded' if restore_preamble else 'asset missing'}")
    print()
    print(f"Wrote:")
    print(f"  {blueprint_path}")
    print(f"  {notes_path}")
    if brief_path:
        print(f"  {brief_path}")
    print()
    print("Next step: the hub Claude reads _BLUEPRINT_SYNTHESIS_NOTES.md and")
    print("synthesizes the TODO sections (1, 3, 4, 6) into project-blueprint.md.")

    return 0


if __name__ == "__main__":
    sys.exit(main())
